name: "Latest blog post"

on:
  schedule:
    - cron: "30 08 * * *"   # 每天 16:30 台灣時間（= 08:30 UTC）
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3          # 建議升到 v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "5"
          # Medium 子網域 → 直接在最後加 /feed
          feed_list: "https://gradient-drift.medium.com/feed"
